# Generated by Django 5.2.1 on 2025-06-05 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="pet",
            new_name="pet_id",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="date_time",
            new_name="time",
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Chưa xác nhận", "Chưa xác nhận"),
                    ("Đã xác nhận", "Đã xác nhận"),
                    ("Đã khám", "Đã khám"),
                    ("Đã hủy", "Đã hủy"),
                ],
                default="Chưa xác nhận",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="appointment",
            table="appointments",
        ),
        migrations.AlterModelTable(
            name="beautyservicehistory",
            table="beauty_service_history",
        ),
        migrations.AlterModelTable(
            name="hotelservicehistory",
            table="hotel_service_history",
        ),
        migrations.AlterModelTable(
            name="medicalhistory",
            table="medical_history",
        ),
        migrations.AlterModelTable(
            name="nutritionplan",
            table="nutrition_plan",
        ),
        migrations.AlterModelTable(
            name="pet",
            table="pets",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
        migrations.AlterModelTable(
            name="vaccinationhistory",
            table="vaccination_history",
        ),
    ]
