# Generated by Django 5.2.1 on 2025-06-05 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_pet_appointment_pet_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="doctor_id",
            new_name="doctor",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="pet_id",
            new_name="pet",
        ),
    ]
