# Generated by Django 5.2.1 on 2025-06-10 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("myapp", "0004_remove_beautyservicehistory_pet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "pet_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("species", models.CharField(max_length=30)),
                ("breed", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("birthdate", models.DateField()),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pets",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.TextField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                            ("owner", "Owner"),
                            ("vet", "Vet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "plan_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("food_type", models.TextField()),
                ("portion", models.TextField()),
                ("special_notes", models.TextField(blank=True, null=True)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.pet"
                    ),
                ),
            ],
            options={
                "db_table": "nutrition_plan",
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diagnosis", models.TextField()),
                ("treatment", models.TextField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_of_visit", models.DateField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.pet"
                    ),
                ),
                (
                    "vet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "db_table": "medical_history",
            },
        ),
        migrations.CreateModel(
            name="HotelServiceHistory",
            fields=[
                (
                    "stay_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("room_number", models.CharField(max_length=10)),
                ("special_care", models.TextField(blank=True, null=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.pet"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_service_history",
            },
        ),
        migrations.CreateModel(
            name="BeautyServiceHistory",
            fields=[
                (
                    "service_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_type", models.CharField(max_length=100)),
                ("service_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.pet"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "db_table": "beauty_service_history",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "appointment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical"),
                            ("beauty", "Beauty"),
                            ("hotel", "Hotel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Chưa xác nhận", "Chưa xác nhận"),
                            ("Đã xác nhận", "Đã xác nhận"),
                            ("Đã khám", "Đã khám"),
                            ("Đã hủy", "Đã hủy"),
                        ],
                        default="Chưa xác nhận",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.pet"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
            },
        ),
        migrations.CreateModel(
            name="VaccinationHistory",
            fields=[
                (
                    "vaccination_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=100)),
                ("date_given", models.DateField()),
                ("next_due", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.pet"
                    ),
                ),
                (
                    "vet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "db_table": "vaccination_history",
            },
        ),
    ]
